### ISSUE TITLE
Getter and Setter Implementation

### ISSUE THREAD

**Issue by namannigam** [flipkart-incubator/Lyrics#23]
https://github.com/flipkart-incubator/Lyrics/blob/3e5f5b0a21cffa767a762e56ea9d5cee87092492/lyrics-core/src/main/java/com/flipkart/lyrics/helper/Helper.java#L68

The default getter and setter implementation of fields like `sProductSuffix` get capitalized names instead for the first lowercase character for the above reason.

Expected:  `getsProductSuffix` and `setsProductSuffix`
Actual: `getSProductSuffix` and `setSProductSuffix`

**Comment by shrey-garg** [comment]
This is intentional
